name: PvPHolograms
main: me.stevetech.pvpholograms.PvPHolograms
version: 0.1
description: Show Holographic Displays with PvPLevels
author: Steve-Tech
api-version: 1.16
depend: [HolographicDisplays, PvPLevels]
commands:
  PvPHolograms:
    aliases: pvpholo
    description: Manage PvPLevels Holograms
    usage: /<command> reload
    permission: PvPHolograms.reload
    permission-message: You don't have permission to use this command!
permissions:
  PvPHolograms.reload:
    description: Reload PvPHolograms' Config
    default: op